### ISSUE TITLE
Not compatible with PHP 5.5 / mysqli

### ISSUE THREAD

**Issue by jantheofel** [terminal42/contao-inputvar#2]
The flag "mysql_real_escape_string" is not compatible with PHP 5.5 / mysqli. In fact it is not compatible with mysqli - and this should be used with PHP 5.5 because mysql throws depecated warnings.

Thus the code needs to be rewritten for mysqli compatibility.

**Comment by aschempp** [comment]
Can you point to a code position? Link a file or something?

**Comment by jantheofel** [comment]
InputVar.php, Line 78 ff.

**Comment by aschempp** [comment]
The whole third parameter is deprecated because Contao 3 does now support InsertTag flags. The only flags not supported by the core are the SQL escape methods. However, [mysqli_real_escape_string](http://ch2.php.net/mysqli_real_escape_string) can't be used in the same sense as the mysql-version, as it requires the `$link` (which we don't have).

**Comment by aschempp** [comment]
http://unmaintained.tech
